
package Package1;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        tf_ocupacion.setEnabled(false);
        tf_horario.setEnabled(false);
        tf_tiempoTrabajado.setEnabled(false);
        tf_sueldo.setEnabled(false);
        this.setLocationRelativeTo(null);
        
        //Modelo - tipo de Persona
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) cb_tipoPersona.getModel();
        modelo.addElement(new Gerente());
        modelo.addElement(new PersonalGeneral());
        cb_tipoPersona.setModel(modelo);
        
        
        //Modelo - Cargo gerente
        DefaultComboBoxModel m2
                = (DefaultComboBoxModel) cb_cargo.getModel();
        m2.addElement("Cargo de Planta");
        m2.addElement("Cargo de Sucursal");
        cb_cargo.setModel(m2);
        
        
        //Modelo - Tipo de Objeto a crear
        DefaultComboBoxModel m3
                = (DefaultComboBoxModel) cb_tipoObjeto.getModel();
        m3.addElement(new Zapato());
        m3.addElement(new Ropa());
        m3.addElement(new Ohogar());
        cb_tipoObjeto.setModel(m3);
        
        
        tf_tallaRopa.setEnabled(false);
        tf_tela.setEnabled(false);
        tf_pais.setEnabled(false);
        
        cb_lugarCasa.setEnabled(false);
        ta_instrucciones.setEnabled(false);
        tf_garantia.setEnabled(false);
        
        
        //Modelo lugar de la casa
        DefaultComboBoxModel m5
                = (DefaultComboBoxModel) cb_lugarCasa.getModel();
        m5.addElement("Sala");
        m5.addElement("Comedor");
        m5.addElement("Baño");
        m5.addElement("Cocina");
     
        //Arbol Personas
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        
        DefaultMutableTreeNode Ptipo1 = new DefaultMutableTreeNode("Gerente");
        DefaultMutableTreeNode Ptipo2 = new DefaultMutableTreeNode("Personal General");
        DefaultMutableTreeNode Gtipo1 = new DefaultMutableTreeNode("Gerente de planta");
        DefaultMutableTreeNode Gtipo2 = new DefaultMutableTreeNode("Gerente de sucursal");
        
        raiz.add(Ptipo1);
        raiz.add(Ptipo2);
        Ptipo1.add(Gtipo1);
        Ptipo1.add(Gtipo2);
        
        m.reload();
        
        
        //Arbol Objetos
        DefaultTreeModel jm2= (DefaultTreeModel) jt_objetos.getModel();
        DefaultMutableTreeNode raiz2
                = (DefaultMutableTreeNode) jm2.getRoot();
        DefaultMutableTreeNode tipo1 = new DefaultMutableTreeNode("Zapato");
        DefaultMutableTreeNode tipo2 = new DefaultMutableTreeNode("Ropa");
        DefaultMutableTreeNode tipo3 = new DefaultMutableTreeNode("Hogar");
        
        raiz2.add(tipo1);
        raiz2.add(tipo2);
        raiz2.add(tipo3);
        
        jm2.reload();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        bg_sexo = new javax.swing.ButtonGroup();
        bg_estado = new javax.swing.ButtonGroup();
        bg_modSexo = new javax.swing.ButtonGroup();
        bg_modEstado = new javax.swing.ButtonGroup();
        tp_principal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_tipoPersona = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_masculino = new javax.swing.JRadioButton();
        rb_femenino = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_soltero = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_userG = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_cargo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_ocupacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_horario = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_tiempoTrabajado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_sueldo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bt_agregarPersona = new javax.swing.JButton();
        pf_password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cb_tipoObjeto = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        bt_colorObjeto = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_tamano = new javax.swing.JTextField();
        tf_calidad = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cb_personaIngreso = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tf_tallaZapato = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_suela = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        tf_comodidad = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_tallaRopa = new javax.swing.JTextField();
        tf_tela = new javax.swing.JTextField();
        tf_pais = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        js_insh = new javax.swing.JScrollPane();
        ta_instrucciones = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        tf_garantia = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        bt_agregarObjeto = new javax.swing.JButton();
        cb_lugarCasa = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        cb_modPersonas = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        tf_modId = new javax.swing.JTextField();
        tf_modNombre = new javax.swing.JTextField();
        tf_modEdad = new javax.swing.JTextField();
        rb_modMasculino = new javax.swing.JRadioButton();
        rb_modFemenino = new javax.swing.JRadioButton();
        rb_modSoltero = new javax.swing.JRadioButton();
        rb_modCasado = new javax.swing.JRadioButton();
        tf_modAltura = new javax.swing.JTextField();
        tf_modPeso = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        tf_modUser = new javax.swing.JTextField();
        tf_modPassword = new javax.swing.JTextField();
        cb_modCargo = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        tf_modOcupacion = new javax.swing.JTextField();
        tf_modHorario = new javax.swing.JTextField();
        tf_modSemanas = new javax.swing.JTextField();
        tf_modSueldo = new javax.swing.JTextField();
        bt_modPersona = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        cb_modObjeto = new javax.swing.JComboBox<>();
        jLabel64 = new javax.swing.JLabel();
        bt_modColor = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_modDescripcion = new javax.swing.JTextArea();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        cb_modPersonaIngreso = new javax.swing.JComboBox<>();
        tf_modMarca = new javax.swing.JTextField();
        tf_modTamano = new javax.swing.JTextField();
        tf_modCalidad = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_modDesSuela = new javax.swing.JTextArea();
        tf_modTallaZapato = new javax.swing.JTextField();
        tf_modComodidad = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        tf_modTallaRopa = new javax.swing.JTextField();
        tf_modTela = new javax.swing.JTextField();
        tf_modPais = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        cb_modDesLugar = new javax.swing.JComboBox<>();
        jLabel80 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_modIns = new javax.swing.JTextArea();
        jLabel81 = new javax.swing.JLabel();
        tf_modGarantia = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_objetos = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_principalStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese los datos de la persona.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de persona:");

        cb_tipoPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoPersonaItemStateChanged(evt);
            }
        });

        jLabel3.setText("ID:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Sexo:");

        bg_sexo.add(rb_masculino);
        rb_masculino.setText("M");

        bg_sexo.add(rb_femenino);
        rb_femenino.setText("F");

        jLabel6.setText("Edad:");

        jLabel7.setText("Estado Civil:");

        rb_soltero.setText("Soltero");

        rb_casado.setText("Casado");

        jLabel8.setText("Altura:");

        jLabel9.setText("cms");

        jLabel10.setText("Peso:");

        jLabel11.setText("Lbs.");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Gerente");

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        jLabel15.setText("Cargo:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Personal General");

        jLabel17.setText("Ocupación:");

        jLabel18.setText("Horario:");

        jLabel19.setText("Tiempo trabajado:");

        jLabel20.setText("semanas");

        jLabel21.setText("Sueldo:");

        jLabel22.setText("Lps.");

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        bt_agregarPersona.setText("Agregar Persona");
        bt_agregarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarPersonaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cb_cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pf_password))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(tf_userG))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rb_soltero)
                        .addGap(18, 18, 18)
                        .addComponent(rb_casado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(rb_masculino)
                        .addGap(18, 18, 18)
                        .addComponent(rb_femenino))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_tipoPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_edad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_altura, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(tf_peso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_ocupacion)
                                    .addComponent(tf_horario, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_sueldo))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(27, 27, 27)
                                        .addComponent(tf_tiempoTrabajado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22))))
                        .addGap(121, 121, 121))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(bt_agregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cb_tipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(rb_masculino)
                                    .addComponent(rb_femenino))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(rb_soltero)
                                    .addComponent(rb_casado))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(bt_agregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_userG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel18))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cb_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(tf_tiempoTrabajado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tp_principal.addTab("Crear Persona", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Ingrese los datos del objeto.");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, -1, -1));

        jLabel24.setText("Tipo de objeto:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 58, -1, -1));

        cb_tipoObjeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoObjetoItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_tipoObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 54, 135, -1));

        jLabel25.setText("Color:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 103, -1, -1));

        bt_colorObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorObjetoMouseClicked(evt);
            }
        });
        jPanel3.add(bt_colorObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 103, 90, 23));

        jLabel26.setText("Descripción:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 145, -1, -1));

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, 55));

        jLabel27.setText("Marca:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 217, -1, -1));
        jPanel3.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 217, 211, -1));

        jLabel28.setText("Tamaño:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 258, -1, -1));

        jLabel29.setText("Calidad:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 296, -1, -1));
        jPanel3.add(tf_tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 255, 210, -1));
        jPanel3.add(tf_calidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 293, 213, -1));

        jLabel30.setText("Persona que lo ingreso:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 342, -1, -1));

        jPanel3.add(cb_personaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 139, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 775, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Zapato");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel32.setText("Talla:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 453, -1, -1));
        jPanel3.add(tf_tallaZapato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 100, -1));

        jLabel33.setText("Descripción suela:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 492, -1, -1));

        ta_suela.setColumns(20);
        ta_suela.setRows(5);
        jScrollPane2.setViewportView(ta_suela);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 113, 63));

        jLabel34.setText("Comodidad [1-10]:");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));
        jPanel3.add(tf_comodidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 45, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Ropa");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 420, -1, -1));

        jLabel36.setText("Talla:");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 456, -1, -1));

        jLabel37.setText("Tipo de tela:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jLabel38.setText("Pais elab:");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 568, -1, -1));
        jPanel3.add(tf_tallaRopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 120, -1));
        jPanel3.add(tf_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 90, -1));
        jPanel3.add(tf_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 100, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Hogar");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 420, -1, -1));

        jLabel40.setText("Descripción:");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jLabel41.setText("Instrucciones:");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        ta_instrucciones.setColumns(20);
        ta_instrucciones.setRows(5);
        js_insh.setViewportView(ta_instrucciones);

        jPanel3.add(js_insh, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 140, 44));

        jLabel42.setText("Garantía:");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, -1, -1));
        jPanel3.add(tf_garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 50, -1));

        jLabel43.setText("meses");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, 20));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setPreferredSize(new java.awt.Dimension(30, 370));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 380));

        bt_agregarObjeto.setText("Agregar Objeto");
        bt_agregarObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarObjetoMouseClicked(evt);
            }
        });
        jPanel3.add(bt_agregarObjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, 60));

        jPanel3.add(cb_lugarCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 130, -1));

        tp_principal.addTab("Crear Objeto", jPanel3);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("Seleccione la persona a modificar:");

        jLabel45.setText("ID:");

        jLabel46.setText("Nombre:");

        jLabel47.setText("Edad:");

        jLabel48.setText("Sexo:");

        jLabel49.setText("Estado Civil:");

        jLabel50.setText("Altura:");

        jLabel51.setText("Peso:");

        bg_modSexo.add(rb_modMasculino);
        rb_modMasculino.setText("M");

        bg_modSexo.add(rb_modFemenino);
        rb_modFemenino.setText("F");

        bg_modEstado.add(rb_modSoltero);
        rb_modSoltero.setText("Soltero");

        bg_modEstado.add(rb_modCasado);
        rb_modCasado.setText("Casado");

        jLabel52.setText("cms");

        jLabel53.setText("Lbs.");

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("Gerente");

        jLabel55.setText("Usuario:");

        jLabel56.setText("Contraseña:");

        jLabel57.setText("Cargo:");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setText("Personal General");

        jLabel59.setText("Ocupación:");

        jLabel60.setText("Horario:");

        jLabel61.setText("Tiempo trabajado:");

        jLabel62.setText("Sueldo:");

        bt_modPersona.setText("Modificar Persona");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(288, 288, 288)
                                .addComponent(jLabel58))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(rb_modSoltero)
                                .addGap(26, 26, 26)
                                .addComponent(rb_modCasado))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel57)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_modCargo, 0, 125, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_modPassword))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_modUser))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel50)
                                            .addComponent(jLabel51))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_modAltura)
                                            .addComponent(tf_modPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel52)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel60)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_modHorario))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel62)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_modSueldo))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel59)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_modOcupacion))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel61)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_modSemanas, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel48)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb_modMasculino)
                                    .addGap(33, 33, 33)
                                    .addComponent(rb_modFemenino))
                                .addComponent(jLabel44))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel47)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_modEdad))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_modNombre))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel45)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_modId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cb_modPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                                .addComponent(bt_modPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_modPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(tf_modId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(tf_modNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(tf_modEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(rb_modMasculino)
                            .addComponent(rb_modFemenino)))
                    .addComponent(bt_modPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(rb_modSoltero)
                    .addComponent(rb_modCasado))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(tf_modAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(tf_modPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel58))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(tf_modUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(tf_modOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(tf_modPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(tf_modHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(cb_modCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(tf_modSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(tf_modSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tp_principal.addTab("Modificar Persona", jPanel4);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("Seleccione el objeto a modificar:");

        jLabel64.setText("Color:");

        jLabel65.setText("Descripción:");

        ta_modDescripcion.setColumns(20);
        ta_modDescripcion.setRows(5);
        jScrollPane5.setViewportView(ta_modDescripcion);

        jLabel66.setText("Marca:");

        jLabel67.setText("Tamaño:");

        jLabel68.setText("Calidad:");

        jLabel69.setText("Persona que lo ingreso:");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setText("Zapato");

        jLabel71.setText("Talla:");

        jLabel72.setText("Descripción suela:");

        jLabel73.setText("Comodidad [1-10]:");

        ta_modDesSuela.setColumns(20);
        ta_modDesSuela.setRows(5);
        jScrollPane6.setViewportView(ta_modDesSuela);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setText("Ropa");

        jLabel75.setText("Talla:");

        jLabel76.setText("Tipo de tela:");

        jLabel77.setText("Pais elab:");

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel78.setText("Hogar");

        jLabel79.setText("Descripción:");

        jLabel80.setText("Instrucciones:");

        ta_modIns.setColumns(20);
        ta_modIns.setRows(5);
        jScrollPane7.setViewportView(ta_modIns);

        jLabel81.setText("Garantia:");

        jLabel82.setText("meses");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addGap(18, 18, 18)
                        .addComponent(bt_modColor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addGap(26, 26, 26)
                        .addComponent(cb_modObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel68)
                                .addComponent(jLabel67))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_modTamano)
                                .addComponent(tf_modCalidad)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel65)
                                .addComponent(jLabel66))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(tf_modMarca))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addGap(18, 18, 18)
                                .addComponent(cb_modPersonaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel71)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                            .addComponent(tf_modTallaZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel72)
                                                .addComponent(jLabel73))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(tf_modComodidad, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel74)
                                        .addGap(134, 134, 134))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel76)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_modTela)
                                                .addGap(28, 28, 28))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel77)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_modPais))
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addComponent(jLabel75)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_modTallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 28, Short.MAX_VALUE)))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel81)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_modGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel82))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel78)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel79)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb_modDesLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel80)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_modObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64)
                    .addComponent(bt_modColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(tf_modMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(tf_modTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(tf_modCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(cb_modPersonaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(jLabel74)
                    .addComponent(jLabel78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(tf_modTallaZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75)
                    .addComponent(tf_modTallaRopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel79)
                    .addComponent(cb_modDesLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel76)
                            .addComponent(tf_modTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(tf_modPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel73)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_modComodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81)
                        .addComponent(tf_modGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel82)))
                .addGap(56, 56, 56))
        );

        tp_principal.addTab("Modificar Objeto", jPanel5);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personas");
        jt_personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_personas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        tp_principal.addTab("Jerarquía de Personas", jPanel6);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Objetos");
        jt_objetos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt_objetos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        tp_principal.addTab("Jerarquía de Objetos", jPanel7);

        getContentPane().add(tp_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipoPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoPersonaItemStateChanged
        if(evt.getStateChange()==2){
            if(cb_tipoPersona.getSelectedItem()instanceof Gerente){
                tf_ocupacion.setEnabled(false);
                tf_horario.setEnabled(false);
                tf_tiempoTrabajado.setEnabled(false);
                tf_sueldo.setEnabled(false);
                tf_userG.setEnabled(true);
                pf_password.setEnabled(true);
                cb_cargo.setEnabled(true);
            }
        } else if(cb_tipoPersona.getSelectedItem() instanceof PersonalGeneral){
            tf_userG.setEnabled(false);
            pf_password.setEnabled(false);
            cb_cargo.setEnabled(false);
            tf_ocupacion.setEnabled(true);
            tf_horario.setEnabled(true);
            tf_tiempoTrabajado.setEnabled(true);
            tf_sueldo.setEnabled(true);    
        }
    }//GEN-LAST:event_cb_tipoPersonaItemStateChanged

    private void bt_agregarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarPersonaMouseClicked
        String id, nombre, sexo, estadoCivil, user, password;
        String cargo ="";
        double altura, peso;
        int edad;
        id=tf_id.getText();
        nombre=tf_nombre.getText();
        if(rb_masculino.isSelected()){
            sexo="M";
        } else{
            sexo="F";
        }
        if(rb_casado.isSelected()){
            estadoCivil="Casado";
        } else{
            estadoCivil="Soltero";
        }
        edad =Integer.parseInt(tf_edad.getText());
        altura=Integer.parseInt(tf_altura.getText());
        peso=Integer.parseInt(tf_peso.getText());
        
        DefaultComboBoxModel m4
                = (DefaultComboBoxModel) cb_personaIngreso.getModel();
        
        Persona p;
        
        if(cb_tipoPersona.getSelectedItem() instanceof Gerente){
            user=tf_userG.getText();
            password = pf_password.getText();
            cargo+=cb_cargo.getSelectedItem();
            p=new Gerente(cargo, password, cargo, id, nombre, sexo, estadoCivil, altura, peso, edad);
            personas.add(p);
            m4.addElement(p.getNombre());
            JOptionPane.showMessageDialog(this, "Gerente agregado exitosamente!");
        } else{
            String ocupacion, horario;
            int semanas;
            double sueldo;
            ocupacion = tf_ocupacion.getText();
            horario=tf_horario.getText();
            semanas=Integer.parseInt(tf_tiempoTrabajado.getText());
            sueldo=Double.parseDouble(tf_sueldo.getText());
            p=new PersonalGeneral(ocupacion, horario, semanas, sueldo, id, nombre, sexo, estadoCivil, altura, peso, edad);
            personas.add(p);
            m4.addElement(p.getNombre());
            JOptionPane.showMessageDialog(this, "Personal General agregado existosamente!");
        }
        
        tf_id.setText("");
        tf_nombre.setText("");
        tf_edad.setText("");
        tf_altura.setText("");
        tf_peso.setText("");
        tf_userG.setText("");
        pf_password.setText("");
        tf_ocupacion.setText("");
        tf_horario.setText("");
        tf_tiempoTrabajado.setText("");
        tf_sueldo.setText("");
    }//GEN-LAST:event_bt_agregarPersonaMouseClicked

    private void cb_tipoObjetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoObjetoItemStateChanged
        if(evt.getStateChange()==2){
            if(cb_tipoObjeto.getSelectedItem() instanceof Zapato){
                tf_tallaRopa.setEnabled(false);
                tf_tela.setEnabled(false);
                tf_pais.setEnabled(false);

                cb_lugarCasa.setEnabled(false);
                ta_instrucciones.setEnabled(false);
                tf_garantia.setEnabled(false);
                
                tf_tallaZapato.setEnabled(true);
                ta_suela.setEnabled(true);
                tf_comodidad.setEnabled(true);
                
            } else if(cb_tipoObjeto.getSelectedItem() instanceof Ropa){
                tf_tallaRopa.setEnabled(true);
                tf_tela.setEnabled(true);
                tf_pais.setEnabled(true);
                
                cb_lugarCasa.setEnabled(false);
                ta_instrucciones.setEnabled(false);
                tf_garantia.setEnabled(false);
                
                tf_tallaZapato.setEnabled(false);
                ta_suela.setEnabled(false);
                tf_comodidad.setEnabled(false);
                
            } else{
                cb_lugarCasa.setEnabled(true);
                ta_instrucciones.setEnabled(true);
                tf_garantia.setEnabled(true);
                
                tf_tallaRopa.setEnabled(false);
                tf_tela.setEnabled(false);
                tf_pais.setEnabled(false);
                
                tf_tallaZapato.setEnabled(false);
                ta_suela.setEnabled(false);
                tf_comodidad.setEnabled(false);
                
            }
        }
    }//GEN-LAST:event_cb_tipoObjetoItemStateChanged

    private void bt_agregarObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarObjetoMouseClicked
        Objeto x;
        Color color;
        double tamano;
        String descripcion, marca, calidad;
        Persona p=new Persona();
        color = bt_colorObjeto.getBackground();
        tamano = Integer.parseInt(tf_tamano.getText());
        descripcion = ta_descripcion.getText();
        marca = tf_marca.getText();
        calidad = tf_calidad.getText();
       
        String p2="";
               p2 +=cb_personaIngreso.getSelectedItem();
        
        for (Persona pe : personas) {
            if(pe.getNombre().equals(p2)){
                p=(Persona)pe;
            }
        }
       
               
        if(cb_tipoObjeto.getSelectedItem() instanceof Zapato){
            double talla=Double.parseDouble(tf_tallaZapato.getText());
            String des = ta_suela.getText();
            int comodidad=Integer.parseInt(tf_comodidad.getText());
            x=new Zapato(talla, des, comodidad, color, descripcion, marca, tamano, calidad, p);
            objetos.add(x);
            JOptionPane.showMessageDialog(this, "Zapato agregado exitosamente!");
        } else if(cb_tipoObjeto.getSelectedItem() instanceof Ropa){
            double talla=Double.parseDouble(tf_tallaRopa.getText());
            String tela = tf_tela.getText();
            String pais = tf_pais.getText();
            x=new Ropa(talla, tela, pais, color, descripcion, marca, tamano, calidad, p);
            objetos.add(x);
            JOptionPane.showMessageDialog(this, "Ropa agregada exitosamente!");
        } else{
            String lugar = "";
            lugar += cb_lugarCasa.getSelectedItem();
            String ins , garantia;
            ins =ta_instrucciones.getText();
            garantia=tf_garantia.getText();
            x=new Ohogar(lugar, ins, garantia, color, descripcion, marca, tamano, calidad, p);
            objetos.add(x);
            JOptionPane.showMessageDialog(this, "Objeto de hogar agregado exitosamente!");
        }
        ta_descripcion.setText("");
        tf_marca.setText("");
        tf_tamano.setText("");
        tf_calidad.setText("");
        
        tf_tallaRopa.setText("");
        tf_tela.setText("");
        tf_pais.setText("");
                
        tf_tallaZapato.setText("");
        ta_suela.setText("");
        tf_comodidad.setText("");
        
        ta_instrucciones.setText("");
        tf_garantia.setText("");
        
    }//GEN-LAST:event_bt_agregarObjetoMouseClicked

    private void bt_colorObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_colorObjetoMouseClicked
        Color c =JColorChooser.showDialog(this, "Elige un color", Color.yellow);
        bt_colorObjeto.setBackground(c);
    }//GEN-LAST:event_bt_colorObjetoMouseClicked

    private void tp_principalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_principalStateChanged
        if(tp_principal.getSelectedIndex()==4){
            DefaultTreeModel model = (DefaultTreeModel) jt_personas.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
            DefaultMutableTreeNode n;
            for (Persona p : personas) {
                DefaultMutableTreeNode nodo= new DefaultMutableTreeNode(p);
                if(p instanceof Gerente){
                    if(((Gerente) p).getCargo().equals("Cargo de Planta")){
                         n=(DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(0);
                         DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Persona)p).getNombre());
                         n.add(x);
                    } else if(((Gerente) p).getCargo().equals("Cargo de Sucursal")){
                        n=(DefaultMutableTreeNode)raiz.getChildAt(0).getChildAt(1);
                        DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Persona)p).getNombre());
                        n.add(x);
                    }
                } else{
                    n=(DefaultMutableTreeNode)raiz.getChildAt(1);
                    DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Persona)p).getNombre());
                    n.add(x);
                }
            }
            model.reload();
        } else if(tp_principal.getSelectedIndex()==5){
            DefaultTreeModel model = (DefaultTreeModel) jt_objetos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) model.getRoot();
            DefaultMutableTreeNode n;
            for (Objeto o : objetos) {
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(o);
                if(o instanceof Zapato){
                    n=(DefaultMutableTreeNode)raiz.getChildAt(0);
                    DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Objeto)o).getMarca());
                    n.add(x);
                } else if(o instanceof Ropa){
                    n=(DefaultMutableTreeNode)raiz.getChildAt(1);
                    DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Objeto)o).getMarca());
                    n.add(x);
                } else{
                    n=(DefaultMutableTreeNode)raiz.getChildAt(2);
                    DefaultMutableTreeNode x = new DefaultMutableTreeNode(((Objeto)o).getMarca());
                    n.add(x);
                }
            }
        }
    }//GEN-LAST:event_tp_principalStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_estado;
    private javax.swing.ButtonGroup bg_modEstado;
    private javax.swing.ButtonGroup bg_modSexo;
    private javax.swing.ButtonGroup bg_sexo;
    private javax.swing.JButton bt_agregarObjeto;
    private javax.swing.JButton bt_agregarPersona;
    private javax.swing.JButton bt_colorObjeto;
    private javax.swing.JButton bt_modColor;
    private javax.swing.JButton bt_modPersona;
    private javax.swing.JComboBox<String> cb_cargo;
    private javax.swing.JComboBox<String> cb_lugarCasa;
    private javax.swing.JComboBox<String> cb_modCargo;
    private javax.swing.JComboBox<String> cb_modDesLugar;
    private javax.swing.JComboBox<String> cb_modObjeto;
    private javax.swing.JComboBox<String> cb_modPersonaIngreso;
    private javax.swing.JComboBox<String> cb_modPersonas;
    private javax.swing.JComboBox<String> cb_personaIngreso;
    private javax.swing.JComboBox<String> cb_tipoObjeto;
    private javax.swing.JComboBox<String> cb_tipoPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane js_insh;
    private javax.swing.JTree jt_objetos;
    private javax.swing.JTree jt_personas;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_femenino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JRadioButton rb_modCasado;
    private javax.swing.JRadioButton rb_modFemenino;
    private javax.swing.JRadioButton rb_modMasculino;
    private javax.swing.JRadioButton rb_modSoltero;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_instrucciones;
    private javax.swing.JTextArea ta_modDesSuela;
    private javax.swing.JTextArea ta_modDescripcion;
    private javax.swing.JTextArea ta_modIns;
    private javax.swing.JTextArea ta_suela;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_calidad;
    private javax.swing.JTextField tf_comodidad;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_garantia;
    private javax.swing.JTextField tf_horario;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modAltura;
    private javax.swing.JTextField tf_modCalidad;
    private javax.swing.JTextField tf_modComodidad;
    private javax.swing.JTextField tf_modEdad;
    private javax.swing.JTextField tf_modGarantia;
    private javax.swing.JTextField tf_modHorario;
    private javax.swing.JTextField tf_modId;
    private javax.swing.JTextField tf_modMarca;
    private javax.swing.JTextField tf_modNombre;
    private javax.swing.JTextField tf_modOcupacion;
    private javax.swing.JTextField tf_modPais;
    private javax.swing.JTextField tf_modPassword;
    private javax.swing.JTextField tf_modPeso;
    private javax.swing.JTextField tf_modSemanas;
    private javax.swing.JTextField tf_modSueldo;
    private javax.swing.JTextField tf_modTallaRopa;
    private javax.swing.JTextField tf_modTallaZapato;
    private javax.swing.JTextField tf_modTamano;
    private javax.swing.JTextField tf_modTela;
    private javax.swing.JTextField tf_modUser;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_pais;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_tallaRopa;
    private javax.swing.JTextField tf_tallaZapato;
    private javax.swing.JTextField tf_tamano;
    private javax.swing.JTextField tf_tela;
    private javax.swing.JTextField tf_tiempoTrabajado;
    private javax.swing.JTextField tf_userG;
    private javax.swing.JTabbedPane tp_principal;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Persona> personas = new ArrayList();
    private ArrayList<Objeto> objetos = new ArrayList();
    
}
